-- HOTFIX — restore the public invoice page (salescommand.app/invoice/:token).
--
-- Regression introduced by 20260625140000_anon_invoices_column_grant.sql, which
-- replaced anon's table-level SELECT on invoices with a 15-column grant to hide
-- stripe_*/qb_*. The column list omitted viewing_token_expires_at.
--
-- Every public-page anon RLS policy on the RELATED tables (proposals,
-- invoice_lines, proposal_wtc, call_log, customers) validates the token with:
--   EXISTS (SELECT 1 FROM invoices i WHERE i.<fk> = ...
--           AND i.viewing_token::text = request_viewing_token()
--           AND i.viewing_token_expires_at IS NOT NULL
--           AND i.viewing_token_expires_at > now())
-- That subquery runs as anon and reads invoices.viewing_token_expires_at. With
-- the column ungranted, it 42501s ("permission denied for table invoices"), so
-- every embed/related read on the public invoice page fails and the page shows
-- "Invoice not found". Symptom started 2026-06-26 (the column-grant migration).
--
-- The same policies also filter invoices on call_log_id (call_log + customers
-- public-view-token policies); proposal_id (proposals/proposal_wtc) and id
-- (invoice_lines) were already in the 140000 grant, but call_log_id and
-- viewing_token_expires_at were NOT — so both must be added here.
--
-- Fix: grant anon SELECT on ONLY viewing_token_expires_at and call_log_id —
-- the two policy-referenced columns 140000 omitted. Both are non-sensitive (an
-- expiry timestamp and a job FK the policies already depend on). stripe_*/qb_*
-- remain ungranted (still hidden from anon) — the #SEC1 boundary is preserved.
-- Do NOT restore the blanket table-level GRANT (that would re-expose pay links).

GRANT SELECT (viewing_token_expires_at, call_log_id) ON public.invoices TO anon;
